#!/bin/bash

#Samuel Lindskog

#script for installation of app

scriptdir=$(dirname $(readlink -f ${BASH_SOURCE:-$0}))

function usage () {
	echo "Usage:"
	echo "installenv (install)"
	echo "installenv -u (uninstall)"
	echo "installenv -e (enable wgifctl.service)"
	echo "installenv -h (help)"

	[[ -z $1 ]] && exit 0
	exit $1
}

eflag="no"
uflag="no"
while getopts ":euh" name; do
	case $name in
		e)
			eflag="yes"
			;;
		u)
			uflag="yes"
			;;
		h)
			usage
			;;
		*)
			usage 1
			;;
	esac
done
shift $((OPTIND - 1))

[[ -n $(systemctl status wgifctl 2>&1 | grep "Active: active") ]] && \
	systemctl disable wgifctl --now

[[ $uflag = "yes" ]] && {
	rm /bin/wgifctl
	rm /etc/wgifctl.conf
	rm /etc/systemd/system/wgifctl.service
	exit 0
}

cp $scriptdir/../env/shell/wgifctl /bin
cp $scriptdir/../env/shell/wgifctl.conf /etc
cp $scriptdir/../env/systemd/wgifctl.service /etc/systemd/system

[[ $eflag = "yes" ]] && systemctl enable wgifctl --now

exit 0
